const defaultData = [
  {'title': 'apple', 'answer': 'apple'},
  {'title': 'banana', 'answer': 'banana'},
  {'title': 'cherry', 'answer': 'cherry'},
  {'title': 'orange', 'answer': 'orange'},
  {'title': 'grape', 'answer': 'grape'},
  {'title': 'kiwi', 'answer': 'kiwi'},
  {'title': 'lemon', 'answer': 'lemon'},
  {'title': 'peach', 'answer': 'peach'},
  {'title': 'pear', 'answer': 'pear'},
  {'title': 'watermelon', 'answer': 'watermelon'},
  {'title': 'strawberry', 'answer': 'strawberry'},
  {'title': 'pineapple', 'answer': 'pineapple'},
  {'title': 'blueberry', 'answer': 'blueberry'},
  {'title': 'raspberry', 'answer': 'raspberry'},
  {'title': 'blackberry', 'answer': 'blackberry'},
  {'title': 'apricot', 'answer': 'apricot'},
  {'title': 'peanut', 'answer': 'peanut'},
  {'title': 'almond', 'answer': 'almond'},
  {'title': 'cashew', 'answer': 'cashew'},
  {'title': 'pistachio', 'answer': 'pistachio'},
  {'title': 'pecan', 'answer': 'pecan'},
  {'title': 'walnut', 'answer': 'walnut'},
  {'title': 'hazelnut', 'answer': 'hazelnut'},
  {'title': 'macadamia', 'answer': 'macadamia'},
  {'title': 'chestnut', 'answer': 'chestnut'},
  {'title': 'carrot', 'answer': 'carrot'},
  {'title': 'potato', 'answer': 'potato'},
  {'title': 'cucumber', 'answer': 'cucumber'},
  {'title': 'tomato', 'answer': 'tomato'},
  {'title': 'onion', 'answer': 'onion'},
  {'title': 'garlic', 'answer': 'garlic'},
  {'title': 'broccoli', 'answer': 'broccoli'},
  {'title': 'cauliflower', 'answer': 'cauliflower'},
  {'title': 'pepper', 'answer': 'pepper'},
  {'title': 'corn', 'answer': 'corn'},
  {'title': 'asparagus', 'answer': 'asparagus'},
  {'title': 'lettuce', 'answer': 'lettuce'},
  {'title': 'cabbage', 'answer': 'cabbage'},
  {'title': 'spinach', 'answer': 'spinach'},
  {'title': 'kale', 'answer': 'kale'},
  {'title': 'celery', 'answer': 'celery'},
  {'title': 'pea', 'answer': 'pea'},
  {'title': 'bean', 'answer': 'bean'},
  {'title': 'soybean', 'answer': 'soybean'},
  {'title': 'lentil', 'answer': 'lentil'},
  {'title': 'chickpea', 'answer': 'chickpea'},
  {'title': 'mushroom', 'answer': 'mushroom'},
  {'title': 'pumpkin', 'answer': 'pumpkin'},
  {'title': 'avocado', 'answer': 'avocado'},
  {'title': 'beetroot', 'answer': 'beetroot'},
  {'title': 'cantaloupe', 'answer': 'cantaloupe'},
  {'title': 'elderberry', 'answer': 'elderberry'},
  {'title': 'fig', 'answer': 'fig'},
  {'title': 'ginger', 'answer': 'ginger'},
  {'title': 'honeydew', 'answer': 'honeydew'},
  {'title': 'kumquat', 'answer': 'kumquat'},
  {'title': 'lychee', 'answer': 'lychee'},
  {'title': 'mandarin', 'answer': 'mandarin'},
  {'title': 'nectarine', 'answer': 'nectarine'},
  {'title': 'okra', 'answer': 'okra'},
  {'title': 'papaya', 'answer': 'papaya'},
  {'title': 'quince', 'answer': 'quince'},
  {'title': 'rhubarb', 'answer': 'rhubarb'},
  {'title': 'starfruit', 'answer': 'starfruit'},
  {'title': 'tangerine', 'answer': 'tangerine'},
  {'title': 'ugli fruit', 'answer': 'ugli fruit'},
  {'title': 'vanilla', 'answer': 'vanilla'},
  {'title': 'watercress', 'answer': 'watercress'},
  {'title': 'yellow squash', 'answer': 'yellow squash'},
  {'title': 'zucchini', 'answer': 'zucchini'},
  {'title': 'artichoke', 'answer': 'artichoke'},
  {'title': 'brussels sprouts', 'answer': 'brussels sprouts'},
  {'title': 'radicchio', 'answer': 'radicchio'},
  {'title': 'endive', 'answer': 'endive'},
  {'title': 'mango', 'answer': 'mango'},
  {'title': 'guava', 'answer': 'guava'},
  {'title': 'jackfruit', 'answer': 'jackfruit'},
  {'title': 'lychee', 'answer': 'lychee'},
  {'title': 'persimmon', 'answer': 'persimmon'},
  {'title': 'star apple', 'answer': 'star apple'},
  {'title': 'pomegranate', 'answer': 'pomegranate'},
  {'title': 'rambutan', 'answer': 'rambutan'},
  {'title': 'soursop', 'answer': 'soursop'},
  {'title': 'tamarind', 'answer': 'tamarind'},
  {'title': 'breadfruit', 'answer': 'breadfruit'},
  {'title': 'cherimoya', 'answer': 'cherimoya'},
  {'title': 'custard apple', 'answer': 'custard apple'},
  {'title': 'durian', 'answer': 'durian'},
  {'title': 'guanabana', 'answer': 'guanabana'},
  {'title': 'longan', 'answer': 'longan'},
  {'title': 'mangosteen', 'answer': 'mangosteen'},
  {'title': 'nance', 'answer': 'nance'},
  {'title': 'sugar apple', 'answer': 'sugar apple'},
  {'title': 'tangelo', 'answer': 'tangelo'},
  {'title': 'wax apple', 'answer': 'wax apple'},
  {'title': 'yellow watermelon', 'answer': 'yellow watermelon'},
];

export default defaultData;